### ISSUE TITLE
Pasture dropdown list problems with special characters

### ISSUE THREAD

**Issue by hindsjj** [rogerlew/rangesat-biomass#20]
On single-year and multi-year pasture analyses, any pastures containing ampersands (&) or underscores ( _ ) fail to generate graphics.

Example: 
https://rangesat.nkn.uidaho.edu/multi-year-stats 
Select ranch: Krebs, Pasture: C & B 
Select ranch: Krebs, Pasture: Derrick_Old Car

**Comment by rogerlew** [comment]
Oh fun, I have sort of a hacky fix for the "Derrick_Old Car" pasture. I need to do some further testing to implement something more robust.

For the "C & B" route it looks like we need to escape the string before passing it off to the API.
![image](https://user-images.githubusercontent.com/3652906/70740372-dbd0f780-1ccd-11ea-9fc2-e749177f3be9.png)

**Comment by hindsjj** [comment]
I've added 'escape(pasture)' to the API urls.  Confirmed that "C & B" is working now.
