### ISSUE TITLE
rogerlew needs an account on production server

### ISSUE THREAD

**Issue by rogerlew** [rogerlew/rangesat-biomass#25]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/3652906/70750862-1ba2d980-1ce4-11ea-9d33-b78f4241f903.png">

- [ ] make rogerlew an account
- [ ] check that works

**Comment by hindsjj** [comment]
Hey Roger -- I think this issue was opened for demonstration purposes.  But if it's a legit issue, I see that you do already have an account.  So let me know if you need any help logging in.
