### ISSUE TITLE
Single-year pasture analysis is not displaying a graph

### ISSUE THREAD

**Issue by hschmalz** [rogerlew/rangesat-biomass#32]
I tried this in both Firefox and Chrome. No graph display in either browser.

**Comment by rogerlew** [comment]
These endpoints are no longer working:
https://rangesat.nkn.uidaho.edu/api/gridmet/single-year-monthly/Zumwalt/TNC/A1/?year=2020&units=English

and

https://rangesat.nkn.uidaho.edu/api/gridmet/annual-progression-monthly/Zumwalt/TNC/A1/?year=2020&units=English

**Comment by rogerlew** [comment]
Further investigation found that the Gridmet route for Palmar's drought sensitivity index is not working for 2020. The single-year-monthly route didn't know how to handle the current year with partial months.

The routes now are fixed, but the frontend needs to be updated to handle the json data from the single-year-monthly route.
